name: reddit
description: A reddit app powered by Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: fonts/Gilroy-HeavyItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Gilroy-Black.ttf
          weight: 800
        - asset: fonts/Gilroy-BlackItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Gilroy-ExtraBold.ttf
          weight: 700
        - asset: fonts/Gilroy-ExtraBoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Gilroy-Bold.ttf
          weight: 600
        - asset: fonts/Gilroy-BoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 500
        - asset: fonts/Gilroy-SemiBoldItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: fonts/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/Gilroy-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: fonts/Gilroy-UltraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: fonts/Gilroy-ThinItalic.ttf
          weight: 100
          style: italic