name: reddit
description: A reddit app powered by Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  draw:
  webview_flutter:
  path:
  flutter_bloc:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/