name: reddit
description: A reddit app powered by Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  intl:
  draw:
  webview_flutter:
  sqflite:
  path:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Heavy.ttf
          weight: 900
        - asset: fonts/Gilroy-Black.ttf
          weight: 800
        - asset: fonts/Gilroy-ExtraBold.ttf
          weight: 700
        - asset: fonts/Gilroy-Bold.ttf
          weight: 600
        - asset: fonts/Gilroy-SemiBold.ttf
          weight: 500
        - asset: fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: fonts/Gilroy-Thin.ttf
          weight: 100
    - family: LinetoCircular
      fonts:
        - asset: fonts/lineto-circular-pro-black.ttf
          weight: 700
        - asset: fonts/lineto-circular-pro-bold.ttf
          weight: 600
        - asset: fonts/lineto-circular-pro-medium.ttf
          weight: 500
        - asset: fonts/lineto-circular-pro-book.ttf
          weight: 400
    - family: Manrope
      fonts:
      - asset: fonts/manrope-extrabold.ttf
        weight: 800
      - asset: fonts/manrope-bold.ttf
        weight: 700
      - asset: fonts/manrope-semibold.ttf
        weight: 600
      - asset: fonts/manrope-medium.ttf
        weight: 500
      - asset: fonts/manrope-regular.ttf
        weight: 400
      - asset: fonts/manrope-light.ttf
        weight: 300
      - asset: fonts/manrope-thin.ttf
        weight: 200