name: reddit
description: A reddit app powered by Flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.0
  draw: ^0.8.0
  flutter_bloc: ^1.0.0
  cached_network_image: ^1.1.2+1
  equatable: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/